Repository Financial-Times/o-icons, pull requests merged in 2021-02, with the labels that each got.

#160 Add new icons
  bower.json
  demos/src/data.json
  src/scss/_icon-list.scss
Labels: component, release:minor

#161 bump ci tools
  package-lock.json
  package.json
Labels: component, release:patch

#163 simplify our dependabot auto-merge system
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
Labels: component
